---
- name: FINAL EXAM - QUESTION 22
  hosts: CSR1kv
  gather_facts: false
  connection: local
 
  tasks:
   - name: FINALEXAM_HOSTNAME_Q22
     ios_config:
       lines: 
         - hostname BALTAZAR

   - name: FINALEXAM_IPV4_Q22
     ios_config:
       parents: "interface GigabitEthernet1"
       lines:
         - ip address 192.168.56.101 255.255.255.0
 
   - name: FINALEXAM_OSPF_Q22
     ios_config:
       parents: "router ospf 1"
       lines:
         - router-id 1.1.1.1
         - network 192.168.56.0 0.0.0.255 area 0